# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5fc606237c2e31db0341ebb0b269ade6ce132b32cb2c4b45254603cdb3a95d91591e9cbe78a81d2639e80b2524e847fccc0a0aefd458caa8c45264f038a58c7

test:
  secret_key_base: fd4092451f2a8200d764d2b38ff4ef328ed55ad1a28fc39dab8f91411837f95bfa1de4fd44d59bccdf40c359ad3a6c9658a5e5eb0d858df6ea34a35df2a20483

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
